from django.urls import path
from .views import *

app_name="main"
urlpatterns = [
    path('', showmain, name="showmain"),
    path('academic/', academic, name="academic"),
    path('volunteer/', volunteer, name="volunteer"),
    path('research/', research, name="research"),
    path('art/', art, name="art"),
    path('fresh/', fresh, name="fresh"),
    path('performance/', performance, name="performance"),
    path('atheletic/', atheletic, name="atheletic"),
    path('social/',social,name='social'),
    path('information/',information,name='information'),
    path('contact/',contact,name='contact'),
    path('likelion/',likelion,name='likelion'),
    path('<str:id>',detail,name='detail'),
    path('new/',new,name='new'),
    path('create/',create,name='create'),
    path('edit/',edit,name='edit'),
    
    path('cafein/',cafein,name='cafein'),
    path('dna/',dna,name='dna'),
    path('dussa/',dussa,name='dussa'),
    path('kcc/',kcc,name='kcc'),
    path('mecs/',mecs,name='mecs'),
    path('nsa/',nsa,name='nsa'),
    path('marx/',marx,name='marx'),

    path('management/',management,name = "management"),
    path('economy/',economy,name='economy'),
    path('international/',international,name='international'),
    path('politics/',politics,name='politics'),

    path('elf/',elf,name='elf'),
    path('rcy/',rcy,name='rcy'),
    path('road/',road,name='road'),
    path('hand/',hand,name='hand'),
    path('neighbor/',neighbor,name='neighbor'),
    path('painters/',painters,name='painters'),
    path('green/',green,name='green'),
    path('korean/',korean,name='korean'),

    path('kusa/',kusa,name='kusa'),
    path('rich/',rich,name='rich'),
    path('unsa/',unsa,name='unsa'),
    path('froniter/',frontier,name='frontier'),
    path('buddha/',buddha,name='buddha'),

    path('dust/',dust,name='dust'),
    path('cave/',cave,name='cave'),
    path('action/',action,name='action'),
    path('wind/',wind,name='wind'),
    path('mountatin/',mountain,name='mountain'),
    path('water/',water,name='water'),
    path('courtist/',courtist,name='courtist'),
    path('dutc/',dutc,name='dutc'),
    path('fctoto/',fctoto,name='fctoto'),
    path('lae/',lae,name='lae'),
    path('kendo/',kendo,name='kendo'),
    path('baduk/',baduk,name='baduk'),
    path('arrow/',dust,name='arrow'),
    path('taekwondo/',taekwondo,name='taekwondo'),
    path('tuskers/',tuskers,name='tuskers'),

    path('ajax/',ajax,name='ajax'),
    path('hola/',hola,name='hola'),
    path('odc/',odc,name='odc'),
    path('opus/',opus,name='opus'),
    path('drama/',drama,name='drama'),
    path('lotus/',lotus,name='lotus'),
    path('cloud/',cloud,name='cloud'),
    path('arirang/',arirang,name='arirang'),
    path('eumsem/',eumsem,name='eumsem'),
    path('fearless/',fearless,name='fearless'),
    path('yeoul/',yeoul,name='yeoul'),

     path('draw/',draw,name='draw'),
    path('literal/',literal,name='literal'),
    path('calligraphy/',calligraphy,name='calligraphy'),
    path('circle/',circle,name='circle'),
    path('stone/',stone,name='stone'),
    path('cartoon/',cartoon,name='cartoon'),
    path('rush/',rush,name='rush'),

    path('elephente/',elephente,name='elephente'),
    path('doomchit/',doomchit,name='doomchit'),
    path('enactus/',enactus,name='enactus'),
    path('jam/',jam,name='jam'),
    path('qud/',qud,name='qud'),

]